export const CONDUIT_TEMPLATE_IDS = {
  RESERVATION_REMINDER: process.env.CONDUIT_TEMPLATE_RESERVATION_REMINDER ?? '',
  REACTIVATION: process.env.CONDUIT_TEMPLATE_REACTIVATION ?? '',
  REACTIVATION_WITH_PROMO:
    process.env.CONDUIT_TEMPLATE_REACTIVATION_PROMO ?? '',
} as const;
